// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzquirxwyogpzvqdudea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cXVpcnh3eW9ncHp2cWR1ZGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDkzMzAsImV4cCI6MjA3Mjc4NTMzMH0.-AwatoS4NC1T2wleR-JIRbPQCJl9oOxY4OjRzUpqNrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});